export const PROJECTS = [
  { name: "Fieldnotes", year: 2020, img: "/img1.jpg" },
  { name: "Redline", year: 2021, img: "/img2.jpg" },
  { name: "Gallery Walk", year: 2019, img: "/img3.jpg" },
  { name: "Side Profile", year: 2022, img: "/img4.jpg" },
  { name: "Open Mic", year: 2023, img: "/img5.jpg" },
  { name: "Backboard", year: 2024, img: "/img6.jpg" },
  { name: "Afterglow", year: 2021, img: "/img7.jpg" },
  { name: "Hill House", year: 2020, img: "/img8.jpg" },
  { name: "Low Tide", year: 2018, img: "/img9.jpg" },
  { name: "Timepiece", year: 2019, img: "/img10.jpg" },
  { name: "Close Focus", year: 2022, img: "/img11.jpg" },
  { name: "Airframe", year: 2023, img: "/img12.jpg" },
  { name: "Hardcase", year: 2024, img: "/img13.jpg" },
  { name: "Deep Red", year: 2021, img: "/img14.jpg" },
  { name: "Fast Track", year: 2022, img: "/img15.jpg" },
  { name: "Night Shift", year: 2025, img: "/img16.jpg" },
];
